spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    hikari:
      jdbc-url: ${JDBC_DATABASE_URL}
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 10
      connection-timeout: 300
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    database: postgresql
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
        ddl-auto: validate #should be temporary